version: '3.7'

services:
  db:
    container_name: noscore-db
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - noscore-network

  reverse-proxy:
    container_name: noscore-reverse-proxy
    image: noscoreio/noscore.reverseproxy:latest
    restart: unless-stopped
    ports:
      - 4000:4000
      - 1337:1337
    expose:
      - 4000
      - 1337
    networks:
      - noscore-network
 
  master:
    container_name: noscore-master
    environment:
      - PORT=5000
      - DB_HOST=host.docker.internal
      - WEBAPI_HOST=http://master
    build:
      context: ./
      dockerfile: deploy/Dockerfile-master
    restart: unless-stopped
    ports:
      - 5000:5000
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/net9.0/linux-musl-x64:/app/build/net9.0
      - ./configuration/:/app/build/configuration   

  world:
    container_name: noscore-world
    environment:
      - WEBAPI_PORT=5001
      - WEBAPI_HOST=http://world
      - WORLD_PORT=1337
      - MASTER_HOST=http://master
      - DB_HOST=host.docker.internal
      - HOST=127.0.0.1
    build:
      context: ./
      dockerfile: deploy/Dockerfile-world
    restart: unless-stopped
    ports:
      - 5001:5001
      - 1337:1337
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/net9.0/linux-musl-x64:/app/build/net9.0
      - ./configuration/:/app/build/configuration   
      
  login:
    container_name: noscore-login
    environment:
      - LOGIN_PORT=4000
      - MASTER_HOST=http://master
      - DB_HOST=host.docker.internal
      - HOST=127.0.0.1
    build:
      context: ./
      dockerfile: deploy/Dockerfile-login
    restart: unless-stopped
    ports:
      - 4000:4000
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/net9.0/linux-musl-x64:/app/build/net9.0
      - ./configuration/:/app/build/configuration   

networks:
  noscore-network:
    driver: bridge
